services:
  - type: web
    name: whatsapp-integration
    env: docker
    buildCommand: docker build -t whatsapp-integration .
    startCommand: docker run -p 3000:3000 whatsapp-integration
    disk:
      name: whatsapp-data
      mountPath: /var/data/whatsapp
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
