services:
  - type: web
    name: whatsapp-integration
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
